### ISSUE TITLE
Convert daily task to use much, much less SQL queries

### ISSUE THREAD

**Issue by orta** [CocoaPods/stats.cocoapods.org#12]
From this:
```
Grabbing stats for: AFNetworking
download
  0.000000   0.000000   0.000000 (  2.050531)
download 7 days
  0.000000   0.000000   0.000000 (  0.669928)
download 30 days
  0.000000   0.000000   0.000000 (  1.740613)
target: application -
  0.000000   0.000000   0.000000 (  4.188445)
target: application - 7 days
  0.000000   0.000000   0.000000 (  1.347112)
target: unit_test_bundle -
  0.000000   0.000000   0.000000 (  4.090567)
target: unit_test_bundle - 7 days
  0.000000   0.000000   0.000000 (  1.214652)
target: app_extension -
  0.000000   0.000000   0.000000 (  4.212791)
target: app_extension - 7 days
  0.000000   0.000000   0.000000 (  1.331190)
target: watch_extension -
  0.000000   0.000000   0.000000 (  4.507111)
target: watch_extension - 7 days
  0.000000   0.000000   0.000000 (  1.152547)
try
  0.000000   0.000000   0.000000 (  1.609165)
try
  0.000000   0.000000   0.000000 (  0.613686)

Totoal:
  0.010000   0.000000   0.010000 ( 30.064178)
```

```
30 seconds * 13 000 = 4.51388889 days
```

To:
``` sql
SELECT
dependency_name,
count(CASE WHEN pod_try THEN 1 ELSE null END) AS try_true,
count(CASE WHEN pod_try THEN null ELSE 1 END) AS try_false
FROM install
GROUP BY dependency_name
```

![screen shot 2015-11-16 at 3 32 37 pm](https://cloud.githubusercontent.com/assets/49038/11194035/e4e55478-8c77-11e5-8afe-27e393c3aa41.png)

**Comment by k0nserv** [comment]
```
SELECT dependency_name, product_type, COUNT(DISTINCT(user_id))
FROM cocoapods_stats_production.install
WHERE pod_try = false
GROUP BY dependency_name, product_type
```

I was thinking of using this and then building a dictionary that lets you get to the stats with `targets[dependency_name][product_type]`. Do you see a reason not to do that?

**Comment by floere** [comment]
@k0nserv No, that's a great idea! (Just using the Array would use less memory)

**Comment by k0nserv** [comment]
But that wouldn't give me fast lookups

**Comment by floere** [comment]
Do you need the lookups? I thought you mainly need to put together update statements for pods?

**Comment by k0nserv** [comment]
I was thinking of maintaining the current logic as much as possible so I'd leave the `metrics_for_pod` method, but have it perform the lookup in lazy loaded hashes

**Comment by floere** [comment]
What about performance? :fire: :fire: :fire: :)

**Comment by k0nserv** [comment]
> Premature optimization is the root of all evil 

When I am finished we'll see if it's fast enough

**Comment by floere** [comment]
> We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%.

The actual quote.

**Comment by floere** [comment]
(I'll stop heckling now)
