### ISSUE TITLE
Pod Try stats are always "null" in the db

### ISSUE THREAD

**Issue by orta** [CocoaPods/stats.cocoapods.org#9]
* could be from the plugin
* could be from stats.cp.org

**Comment by orta** [comment]
doesn't look like there's a test specifically around pod try on stats.cp.org

**Comment by orta** [comment]
I added a quick test for it on stats, looks like it's working fine, must be not coming from the client

**Comment by segiddins** [comment]
Yeah, come to the same conclusion, but I'm not sure why

**Comment by segiddins** [comment]
Fixed in the client
